### ISSUE TITLE
Hangs on execution

### ISSUE THREAD

**Issue by IrcDirk** [kdar/profilelcp#1]
This tool hangs on execution on both windows/linux, maybe something changed in other packages... Can u check whats wrong?

**Comment by kdar** [comment]
You're right. Haven't used it in a while, let me look into it.

**Comment by IrcDirk** [comment]
Thanks for very quick reply :) Was just searching for honorbuddy randomizer and i found yours.

**Comment by kdar** [comment]
fixed
